version: '2'
services:
    school-webapp:
        build: .
        container_name: "school-webapp"
        image: debian/latest
        ports:
            - 1337:1337
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet